create or replace PACKAGE PKG_USUARIO AS

    PROCEDURE SP_VALIDAR_CREDENCIALES(
        P_NUM OUT INTEGER,
        P_ID_USUARIO IN USUARIO.ID_USUARIO%TYPE,
        P_CLAVE IN USUARIO.CLAVE%TYPE
    );  

END PKG_USUARIO;

create or replace PACKAGE BODY PKG_USUARIO AS

    PROCEDURE SP_VALIDAR_CREDENCIALES(
        P_NUM OUT INTEGER,
        P_ID_USUARIO IN USUARIO.ID_USUARIO%TYPE,
        P_CLAVE IN USUARIO.CLAVE%TYPE
    )AS
    BEGIN
        SELECT COUNT(*) INTO P_NUM
        FROM USUARIO
        WHERE
            ID_USUARIO = P_ID_USUARIO AND
            CLAVE = P_CLAVE AND
            ESTADO = '1';
    END SP_VALIDAR_CREDENCIALES;

END PKG_USUARIO;