CREATE TABLE CLIENTE(
  ID_CLIENTE NUMERIC(10,0) NOT NULL PRIMARY KEY,
  RAZON_SOCIAL VARCHAR2(240) NOT NULL UNIQUE,
  RUC CHAR(11) NOT NULL UNIQUE,
  DIRECCION VARCHAR2(280) NOT NULL,
  ESTADO CHAR(1) DEFAULT '1'
);

INSERT INTO CLIENTE(ID_CLIENTE,RAZON_SOCIAL,RUC, DIRECCION) VALUES (1,'GALAXY TRAINING','20544987306','AV. AREQUIPA 330 OFI. 801');
INSERT INTO CLIENTE(ID_CLIENTE,RAZON_SOCIAL,RUC, DIRECCION) VALUES (2,'TELEFONICA DEL PERU S.A.','20100017491','Av. Juan de Arona N° 786');
COMMIT;
SELECT * FROM CLIENTE;

