CREATE TABLE USUARIO (
	ID_USUARIO VARCHAR2(100) PRIMARY KEY, 
	CLAVE VARCHAR2(100) NOT NULL, 
	ESTADO CHAR(1) DEFAULT '1'
);

INSERT INTO USUARIO (ID_USUARIO,CLAVE,ESTADO) values ('cgomez','1234ABCD','1');