CREATE TABLE VEHICULO (
    CODIGO NUMERIC(10,0) NOT NULL PRIMARY KEY,
    PLACA VARCHAR2(20) NOT NULL,
    ANO NUMERIC(5,0) NOT NULL,
    ESTADO CHAR(1) DEFAULT '1'
);

INSERT INTO VEHICULO (CODIGO,PLACA,ANO) VALUES (SEQ_VEHICULO.NEXTVAL,'A1A-123',2015);
INSERT INTO VEHICULO (CODIGO,PLACA,ANO) VALUES (SEQ_VEHICULO.NEXTVAL,'C1F-423',2001);
INSERT INTO VEHICULO (CODIGO,PLACA,ANO) VALUES (SEQ_VEHICULO.NEXTVAL,'D3F-365',2001);