CREATE TABLE VEHICULO (
    CODIGO NUMERIC(10,0) PRIMARY KEY,
    PLACA VARCHAR2(20) NOT NULL,
    MARCA VARCHAR2(100) NOT NULL,
    MODELO VARCHAR(100) NOT NULL,
    ANO NUMERIC(5,0) NOT NULL,
    ESTADO CHAR(1) DEFAULT '1'
);

INSERT INTO VEHICULO (CODIGO,PLACA,MARCA,MODELO,ANO) VALUES (SEQ_VEHICULO.NEXTVAL,'A1A-123','SUZUKI','SWIFT',2015);
INSERT INTO VEHICULO (CODIGO,PLACA,MARCA,MODELO,ANO) VALUES (SEQ_VEHICULO.NEXTVAL,'C1F-423','HIUNDAY','TUCSON',2001);
INSERT INTO VEHICULO (CODIGO,PLACA,MARCA,MODELO,ANO) VALUES (SEQ_VEHICULO.NEXTVAL,'D3F-365','VOLKS-WAGEN','GOL',2001);